"""Case / CaseAlert: the persistent SOC case-management domain (Step 12R,
architecture approved in Step 12Q).

Domain distinction (do not collapse these — see Step 12Q's own report):
  SecurityEvent — telemetry: what happened.
  DetectionResult — a detection decision: why the behavior is suspicious.
                     Ephemeral, never persisted.
  Alert — a trackable investigation item. Persisted, carries its own
          lifecycle (app.schemas.alert.AlertStatus), unchanged by this step.
  InvestigationContext — deterministic, computed-on-demand evidence view
          over one Alert. Never persisted, unchanged by this step.
  Case — a persistent operational container ABOVE Alert: groups related
          alerts, tracks its OWN lifecycle/ownership, independent of any
          single alert's own status. Not a renamed Alert.

Field/constraint conventions below are a deliberate structural copy of
app.models.alert.Alert and app.models.admin_audit.AdminAudit — UUID PK
with server-side gen_random_uuid(), timezone-aware DateTime columns,
String + DB CHECK for the small fixed status/priority vocabularies
(never a separate lookup table), `updated_at` present because (like
Alert, unlike append-only SecurityEvent) a Case's fields legitimately
change after creation.

`case_number` is a human-readable DISPLAY identifier only — generated by
a native PostgreSQL SEQUENCE (never COUNT(*)/max()+1, which would race
under concurrent creation) so it is guaranteed unique without any
read-then-write window. It is never used as a foreign-key target and
never accepted as client input; `id` (UUID) remains the sole
authoritative identity for every relationship, route, and audit
reference — see the Step 12Q report's own explicit caution on this
point.

Case.severity is deliberately NOT a column here — it is a derived,
read-only view (max severity among currently-linked alerts) computed by
CaseService at query time, never stored, so it can never drift from the
alerts it summarizes. See CaseService.derive_severity().
"""

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, Integer, Sequence, String, Text, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base

# Registered as a genuine PostgreSQL SEQUENCE object (not a Python-side
# counter): Base.metadata.create_all() (the test-database bootstrap path,
# see tests/conftest.py) creates it automatically as a dependency of the
# `case_number` column below; the real Alembic migration creates it
# explicitly (autogenerate does not synthesize sequences from column
# metadata) — see that migration's own comment for why this is a
# deliberate manual-DDL element.
CASE_NUMBER_SEQUENCE = Sequence("case_number_seq")

# The complete, fixed lifecycle vocabulary (Step 12Q, approved). No
# CONTAINMENT state — see the Step 12Q report for why that was rejected.
CASE_STATUS_VALUES = ("OPEN", "INVESTIGATING", "RESOLVED", "CLOSED")

# The complete, fixed priority vocabulary — reuses DetectionSeverity's own
# lowercase vocabulary shape for platform-wide consistency (Step 12Q),
# even though this is an independent, analyst-set operational field, not
# a copy of any alert's severity.
CASE_PRIORITY_VALUES = ("critical", "high", "medium", "low")


class Case(Base):
    """A persistent SOC operational container grouping related Alerts and
    tracking its own lifecycle/ownership. See this module's own docstring
    for the full domain distinction from Alert/Investigation.
    """

    __tablename__ = "cases"
    __table_args__ = (
        Index("ix_cases_status", "status"),
        Index("ix_cases_priority", "priority"),
        Index("ix_cases_owner_id", "owner_id"),
        Index("ix_cases_created_at", "created_at"),
        CheckConstraint("length(btrim(title)) > 0", name="ck_cases_title_not_blank"),
        CheckConstraint("length(btrim(description)) > 0", name="ck_cases_description_not_blank"),
        CheckConstraint(
            "status IN (" + ", ".join(f"'{v}'" for v in CASE_STATUS_VALUES) + ")",
            name="ck_cases_status_valid",
        ),
        CheckConstraint(
            "priority IN (" + ", ".join(f"'{v}'" for v in CASE_PRIORITY_VALUES) + ")",
            name="ck_cases_priority_valid",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )

    # Human-readable display identifier only — see this module's own
    # docstring. Never a FK target, never client-suppliable.
    case_number: Mapped[int] = mapped_column(
        Integer,
        CASE_NUMBER_SEQUENCE,
        server_default=CASE_NUMBER_SEQUENCE.next_value(),
        nullable=False,
        unique=True,
    )

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    status: Mapped[str] = mapped_column(String(20), nullable=False, server_default=text("'OPEN'"))
    priority: Mapped[str] = mapped_column(String(20), nullable=False, server_default=text("'medium'"))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Immutable provenance — server-resolved from AuthenticatedUser at
    # creation, never client-suppliable, never mutated afterward.
    created_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )

    # Nullable: "unowned" is a normal, common state (a freshly created or
    # freshly released case). RESTRICT (not CASCADE/SET NULL): a
    # historical owner must remain attributable even after later
    # deactivation — mirrors AdminAudit's actor/target FK reasoning
    # exactly (AMNIX has no user-deletion endpoint, so this is a guard
    # against a future one silently erasing ownership history).
    owner_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="RESTRICT"), nullable=True
    )

    # Set by CaseService only when entering CLOSED; cleared (NULL) when
    # reopening CLOSED -> INVESTIGATING. Nullable in the DB — the "must be
    # non-blank when closing" rule is enforced by CaseService, not a
    # blanket NOT NULL, exactly mirroring how Alert's own transition
    # rules live in a service, not a schema constraint.
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class CaseAlert(Base):
    """The Alert <-> Case many-to-many join, mirroring
    app.models.alert.alert_security_events' proven shape exactly
    (composite PK of both FKs, so a duplicate link is impossible at the
    database level regardless of request timing) — but modeled as a
    genuine mapped class (an "association object"), not a bare
    secondary Table, because this relationship carries its own real
    columns (`linked_at`/`linked_by`) that a plain association table
    cannot hold.

    Deletion behavior mirrors alert_security_events' own asymmetric
    reasoning: `case_id` CASCADE (a link row has no independent meaning
    once its Case is gone), `alert_id` RESTRICT (deleting an Alert that
    is still cited by a Case must fail loudly, never silently erase the
    case's own evidence trail) — Alert deletion does not exist anywhere
    in AMNIX today, so this is a deliberate guard, not a reachable path.
    """

    __tablename__ = "case_alerts"
    __table_args__ = (Index("ix_case_alerts_alert_id", "alert_id"),)

    case_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cases.id", ondelete="CASCADE"), primary_key=True
    )
    alert_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("alerts.id", ondelete="RESTRICT"), primary_key=True
    )

    linked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    linked_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
