import { getRuleDefinition } from '@/features/rules/ruleRegistry'
import type { AlertRead, AlertStatus, DetectionSeverity } from '@/types/api'

/** DERIVED ANALYST VIEWS built entirely from the one real, bounded
 * GET /alerts response the Detection Operations page fetches -- never
 * a historical total, never a second data source. Severity/status
 * counts intentionally include every real enum value (even at zero)
 * so the UI can render an honest "No X alerts returned in this view"
 * rather than omitting a row and implying it doesn't exist.
 */

const SEVERITY_ORDER: DetectionSeverity[] = ['critical', 'high', 'medium', 'low']
const STATUS_ORDER: AlertStatus[] = ['new', 'escalated', 'investigating', 'acknowledged', 'resolved']

export interface SeverityCount {
  severity: DetectionSeverity
  count: number
}

export function deriveSeverityDistribution(alerts: AlertRead[]): SeverityCount[] {
  const counts = new Map<DetectionSeverity, number>(SEVERITY_ORDER.map((s) => [s, 0]))
  for (const alert of alerts) counts.set(alert.severity, (counts.get(alert.severity) ?? 0) + 1)
  return SEVERITY_ORDER.map((severity) => ({ severity, count: counts.get(severity) ?? 0 }))
}

export interface StatusCount {
  status: AlertStatus
  count: number
}

export function deriveStatusDistribution(alerts: AlertRead[]): StatusCount[] {
  const counts = new Map<AlertStatus, number>(STATUS_ORDER.map((s) => [s, 0]))
  for (const alert of alerts) counts.set(alert.status, (counts.get(alert.status) ?? 0) + 1)
  return STATUS_ORDER.map((status) => ({ status, count: counts.get(status) ?? 0 }))
}

export interface RuleActivity {
  ruleId: string
  /** Real rule name from the Step 12H static registry, or null if this
   * rule_id isn't in that registry -- callers must fall back to the
   * raw, backend-authoritative rule_id text, never a fabricated name. */
  ruleName: string | null
  /** The severity observed on alerts actually returned for this
   * rule_id in this window -- REAL OBSERVED DATA, not the static
   * registry's own severity field (kept independent deliberately, so
   * this reflects what actually happened, not what the rule is
   * configured to produce). */
  observedSeverity: DetectionSeverity
  recentAlertCount: number
}

/** Groups the real, already-fetched alerts by rule_id and sorts by
 * bounded observed count (descending) -- "alerts returned in selected
 * window," never "total alerts generated by rule."
 */
export function deriveRuleActivity(alerts: AlertRead[]): RuleActivity[] {
  const byRule = new Map<string, { count: number; severity: DetectionSeverity }>()
  for (const alert of alerts) {
    const entry = byRule.get(alert.rule_id)
    if (entry) entry.count += 1
    else byRule.set(alert.rule_id, { count: 1, severity: alert.severity })
  }
  return Array.from(byRule.entries())
    .map(([ruleId, entry]) => ({
      ruleId,
      ruleName: getRuleDefinition(ruleId)?.name ?? null,
      observedSeverity: entry.severity,
      recentAlertCount: entry.count,
    }))
    .sort((a, b) => b.recentAlertCount - a.recentAlertCount)
}

export interface ActivityBucket {
  bucketStart: string
  counts: Record<DetectionSeverity, number>
  total: number
}

/** Buckets real alert.first_seen timestamps into fixed-width windows
 * for the Alert Activity visualization -- a view of THIS bounded
 * dataset only. An empty bucket means no alert in this page's result
 * set fell into that slot; it is never asserted as proof that zero
 * alerts occurred globally during that time (the underlying GET
 * /alerts response is itself bounded by `limit`).
 */
export function deriveActivityTimeline(alerts: AlertRead[], windowMinutes: number, now: Date = new Date()): ActivityBucket[] {
  const bucketMinutes = windowMinutes <= 15 ? 5 : windowMinutes <= 60 ? 10 : 60
  const bucketCount = Math.ceil(windowMinutes / bucketMinutes)
  const bucketMs = bucketMinutes * 60_000
  const windowStartMs = now.getTime() - windowMinutes * 60_000

  const buckets: ActivityBucket[] = Array.from({ length: bucketCount }, (_, i) => ({
    bucketStart: new Date(windowStartMs + i * bucketMs).toISOString(),
    counts: { critical: 0, high: 0, medium: 0, low: 0 },
    total: 0,
  }))

  for (const alert of alerts) {
    const t = new Date(alert.first_seen).getTime()
    if (t < windowStartMs || t > now.getTime()) continue
    const index = Math.min(bucketCount - 1, Math.floor((t - windowStartMs) / bucketMs))
    buckets[index].counts[alert.severity] += 1
    buckets[index].total += 1
  }

  return buckets
}
