"""create users table

Revision ID: 04dc39d2b93b
Revises: f68537ab8411
Create Date: 2026-09-05 22:15:31.129084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04dc39d2b93b'
down_revision: Union[str, Sequence[str], None] = 'f68537ab8411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("password_hash ~ '^\\$argon2id\\$'", name='ck_users_password_hash_is_argon2id'),
    sa.CheckConstraint("role IN ('analyst', 'admin')", name='ck_users_role_valid'),
    sa.CheckConstraint('length(btrim(email)) > 0', name='ck_users_email_not_blank'),
    sa.CheckConstraint('length(btrim(password_hash)) > 0', name='ck_users_password_hash_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
