"""add case scope to copilot audits

Revision ID: 28ed68e349fe
Revises: fcde657fb084
Create Date: 2026-09-15 01:01:23.162531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ed68e349fe'
down_revision: Union[str, Sequence[str], None] = 'fcde657fb084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilot_audits', sa.Column('case_id', sa.UUID(), nullable=True))
    op.alter_column('copilot_audits', 'alert_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_copilot_audits_case_id', 'copilot_audits', ['case_id'], unique=False)
    op.create_foreign_key(
        'fk_copilot_audits_case_id_cases', 'copilot_audits', 'cases', ['case_id'], ['id'], ondelete='CASCADE'
    )
    op.create_check_constraint('ck_copilot_audits_exactly_one_scope', 'copilot_audits', '(alert_id IS NOT NULL AND case_id IS NULL) OR (alert_id IS NULL AND case_id IS NOT NULL)')
    # ### end Alembic commands ###

    # Manually added — alembic autogenerate does not detect a changed
    # CHECK constraint BODY when the constraint name is unchanged (see
    # app.models.copilot_audit's own Step 13D docstring section for why
    # both of these widen rather than just referencing new columns):
    # request_type gains 'case_brief', and history_turn_count's
    # NULL-only rule now also covers 'case_brief' rows (which, like
    # 'ask', never carry conversation history).
    op.drop_constraint('ck_copilot_audits_request_type_valid', 'copilot_audits', type_='check')
    op.create_check_constraint(
        'ck_copilot_audits_request_type_valid',
        'copilot_audits',
        "request_type IN ('ask', 'follow_up', 'case_brief')",
    )
    op.drop_constraint('ck_copilot_audits_history_turn_count_only_for_follow_up', 'copilot_audits', type_='check')
    op.create_check_constraint(
        'ck_copilot_audits_history_turn_count_only_for_follow_up',
        'copilot_audits',
        "(request_type IN ('ask', 'case_brief') AND history_turn_count IS NULL) OR (request_type = 'follow_up')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Reverse of the two manually-added CHECK constraint updates above —
    # restore the pre-Step-13D constraint bodies first, before the
    # auto-generated commands below drop case_id/loosen alert_id (a
    # 'case_brief' row, or a NULL-alert_id row, would violate the
    # restored constraints, so this order matters: an operator running
    # this downgrade against a database that already has real
    # case-scoped rows will correctly fail here rather than silently
    # corrupting them).
    op.drop_constraint('ck_copilot_audits_history_turn_count_only_for_follow_up', 'copilot_audits', type_='check')
    op.create_check_constraint(
        'ck_copilot_audits_history_turn_count_only_for_follow_up',
        'copilot_audits',
        "(request_type = 'ask' AND history_turn_count IS NULL) OR (request_type = 'follow_up')",
    )
    op.drop_constraint('ck_copilot_audits_request_type_valid', 'copilot_audits', type_='check')
    op.create_check_constraint(
        'ck_copilot_audits_request_type_valid', 'copilot_audits', "request_type IN ('ask', 'follow_up')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_copilot_audits_exactly_one_scope', 'copilot_audits', type_='check')
    op.drop_constraint('fk_copilot_audits_case_id_cases', 'copilot_audits', type_='foreignkey')
    op.drop_index('ix_copilot_audits_case_id', table_name='copilot_audits')
    op.alter_column('copilot_audits', 'alert_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('copilot_audits', 'case_id')
    # ### end Alembic commands ###
