"""create admin_audits table

Revision ID: 3e4b1832509a
Revises: a2deb2e69610
Create Date: 2026-09-09 13:14:47.230949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4b1832509a'
down_revision: Union[str, Sequence[str], None] = 'a2deb2e69610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('previous_is_active', sa.Boolean(), nullable=False),
    sa.Column('new_is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('USER_STATUS_CHANGED')", name='ck_admin_audits_action_valid'),
    sa.CheckConstraint('actor_user_id != target_user_id', name='ck_admin_audits_actor_not_target'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_audits_actor_user_id', 'admin_audits', ['actor_user_id'], unique=False)
    op.create_index('ix_admin_audits_created_at', 'admin_audits', ['created_at'], unique=False)
    op.create_index('ix_admin_audits_target_user_id', 'admin_audits', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_audits_target_user_id', table_name='admin_audits')
    op.drop_index('ix_admin_audits_created_at', table_name='admin_audits')
    op.drop_index('ix_admin_audits_actor_user_id', table_name='admin_audits')
    op.drop_table('admin_audits')
    # ### end Alembic commands ###
