"""add case follow-up request type to copilot audits

Revision ID: 5adf30c8bc46
Revises: 28ed68e349fe
Create Date: 2026-09-15 20:37:29.781468

Step 13E: Case-scoped follow-up conversation (CaseCopilotService.
ask_case_follow_up) adds a fourth AuditRequestType value, 'case_follow_up'
-- the Case-scoped counterpart to 'follow_up'. Alembic autogenerate does
not detect a changed CHECK constraint BODY when the constraint name is
unchanged (see the previous migration, 28ed68e349fe, for the identical
situation the first time this happened) -- both widenings below are
therefore manually authored, not autogenerated. Purely additive: no
column, table, or index changes; no existing row's data changes shape.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adf30c8bc46'
down_revision: Union[str, Sequence[str], None] = '28ed68e349fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint('ck_copilot_audits_request_type_valid', 'copilot_audits', type_='check')
    op.create_check_constraint(
        'ck_copilot_audits_request_type_valid',
        'copilot_audits',
        "request_type IN ('ask', 'follow_up', 'case_brief', 'case_follow_up')",
    )
    op.drop_constraint('ck_copilot_audits_history_turn_count_only_for_follow_up', 'copilot_audits', type_='check')
    op.create_check_constraint(
        'ck_copilot_audits_history_turn_count_only_for_follow_up',
        'copilot_audits',
        "(request_type IN ('ask', 'case_brief') AND history_turn_count IS NULL) "
        "OR (request_type IN ('follow_up', 'case_follow_up'))",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Restore the pre-Step-13E constraint bodies. An operator running this
    # downgrade against a database that already has real 'case_follow_up'
    # rows will correctly fail here (those rows violate the narrower
    # restored CHECK) rather than silently corrupting them -- same
    # ordering discipline as migration 28ed68e349fe's own downgrade.
    op.drop_constraint('ck_copilot_audits_history_turn_count_only_for_follow_up', 'copilot_audits', type_='check')
    op.create_check_constraint(
        'ck_copilot_audits_history_turn_count_only_for_follow_up',
        'copilot_audits',
        "(request_type IN ('ask', 'case_brief') AND history_turn_count IS NULL) OR (request_type = 'follow_up')",
    )
    op.drop_constraint('ck_copilot_audits_request_type_valid', 'copilot_audits', type_='check')
    op.create_check_constraint(
        'ck_copilot_audits_request_type_valid',
        'copilot_audits',
        "request_type IN ('ask', 'follow_up', 'case_brief')",
    )
