"""create alerts table and alert_security_events association

Revision ID: afe270be840b
Revises: c2b88fc3f5f4
Create Date: 2026-08-25 21:45:23.982137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afe270be840b'
down_revision: Union[str, Sequence[str], None] = 'c2b88fc3f5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("confidence IN ('low', 'medium', 'high')", name='ck_alerts_confidence_valid'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name='ck_alerts_severity_valid'),
    sa.CheckConstraint("status IN ('new', 'acknowledged', 'investigating', 'resolved', 'escalated')", name='ck_alerts_status_valid'),
    sa.CheckConstraint('length(btrim(rule_id)) > 0', name='ck_alerts_rule_id_not_blank'),
    sa.CheckConstraint('length(btrim(title)) > 0', name='ck_alerts_title_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_first_seen', 'alerts', ['first_seen'], unique=False)
    op.create_index('ix_alerts_rule_id', 'alerts', ['rule_id'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('alert_security_events',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('security_event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_event_id'], ['security_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('alert_id', 'security_event_id')
    )
    op.create_index('ix_alert_security_events_security_event_id', 'alert_security_events', ['security_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_security_events_security_event_id', table_name='alert_security_events')
    op.drop_table('alert_security_events')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_rule_id', table_name='alerts')
    op.drop_index('ix_alerts_first_seen', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
