"""create security_events table

Revision ID: c2b88fc3f5f4
Revises: 
Create Date: 2026-08-25 15:15:12.506199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2b88fc3f5f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_ip', postgresql.INET(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=500), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('parent_process_name', sa.String(length=500), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IS NULL OR severity IN ('informational', 'low', 'medium', 'high', 'critical')", name='ck_security_events_severity_valid'),
    sa.CheckConstraint('destination_port IS NULL OR (destination_port >= 0 AND destination_port <= 65535)', name='ck_security_events_destination_port_range'),
    sa.CheckConstraint('length(btrim(event_type)) > 0', name='ck_security_events_event_type_not_blank'),
    sa.CheckConstraint('length(btrim(source)) > 0', name='ck_security_events_source_not_blank'),
    sa.CheckConstraint('source_port IS NULL OR (source_port >= 0 AND source_port <= 65535)', name='ck_security_events_source_port_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_destination_ip', 'security_events', ['destination_ip'], unique=False)
    op.create_index('ix_security_events_event_timestamp', 'security_events', ['event_timestamp'], unique=False)
    op.create_index('ix_security_events_event_type', 'security_events', ['event_type'], unique=False)
    op.create_index('ix_security_events_hostname', 'security_events', ['hostname'], unique=False)
    op.create_index('ix_security_events_source', 'security_events', ['source'], unique=False)
    op.create_index('ix_security_events_source_ip', 'security_events', ['source_ip'], unique=False)
    op.create_index('ix_security_events_username', 'security_events', ['username'], unique=False)
    op.create_index('uq_security_events_source_dedup', 'security_events', ['source', 'source_event_id'], unique=True, postgresql_where=sa.text('source_event_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_security_events_source_dedup', table_name='security_events', postgresql_where=sa.text('source_event_id IS NOT NULL'))
    op.drop_index('ix_security_events_username', table_name='security_events')
    op.drop_index('ix_security_events_source_ip', table_name='security_events')
    op.drop_index('ix_security_events_source', table_name='security_events')
    op.drop_index('ix_security_events_hostname', table_name='security_events')
    op.drop_index('ix_security_events_event_type', table_name='security_events')
    op.drop_index('ix_security_events_event_timestamp', table_name='security_events')
    op.drop_index('ix_security_events_destination_ip', table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
