"""create copilot_audits table

Revision ID: f68537ab8411
Revises: afe270be840b
Create Date: 2026-09-03 00:29:29.736394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68537ab8411'
down_revision: Union[str, Sequence[str], None] = 'afe270be840b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_audits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=False),
    sa.Column('question_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('question_length', sa.Integer(), nullable=False),
    sa.Column('history_turn_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(outcome = 'success' AND http_status = 200 AND validation_status = 'passed') OR (outcome = 'failure' AND http_status = 502 AND validation_status IN ('failed', 'not_applicable'))", name='ck_copilot_audits_outcome_http_validation_consistency'),
    sa.CheckConstraint("(request_type = 'ask' AND history_turn_count IS NULL) OR (request_type = 'follow_up')", name='ck_copilot_audits_history_turn_count_only_for_follow_up'),
    sa.CheckConstraint("outcome IN ('success', 'failure')", name='ck_copilot_audits_outcome_valid'),
    sa.CheckConstraint("question_fingerprint ~ '^[0-9a-f]{64}$'", name='ck_copilot_audits_question_fingerprint_sha256_hex'),
    sa.CheckConstraint("request_type IN ('ask', 'follow_up')", name='ck_copilot_audits_request_type_valid'),
    sa.CheckConstraint("validation_status IN ('passed', 'failed', 'not_applicable')", name='ck_copilot_audits_validation_status_valid'),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='ck_copilot_audits_duration_ms_non_negative'),
    sa.CheckConstraint('history_turn_count IS NULL OR history_turn_count >= 0', name='ck_copilot_audits_history_turn_count_non_negative'),
    sa.CheckConstraint('http_status IN (200, 502)', name='ck_copilot_audits_http_status_valid'),
    sa.CheckConstraint('length(btrim(provider_name)) > 0', name='ck_copilot_audits_provider_name_not_blank'),
    sa.CheckConstraint('model_name IS NULL OR length(btrim(model_name)) > 0', name='ck_copilot_audits_model_name_not_blank'),
    sa.CheckConstraint('question_length >= 0', name='ck_copilot_audits_question_length_non_negative'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_copilot_audits_alert_id', 'copilot_audits', ['alert_id'], unique=False)
    op.create_index('ix_copilot_audits_created_at', 'copilot_audits', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_copilot_audits_created_at', table_name='copilot_audits')
    op.drop_index('ix_copilot_audits_alert_id', table_name='copilot_audits')
    op.drop_table('copilot_audits')
    # ### end Alembic commands ###
