"""create case management tables

Revision ID: fcde657fb084
Revises: 3e4b1832509a
Create Date: 2026-09-12 22:47:05.849227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcde657fb084'
down_revision: Union[str, Sequence[str], None] = '3e4b1832509a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-added: Alembic's autogenerate detects the `case_number` column's
    # server_default (nextval('case_number_seq')) but does not synthesize
    # the CREATE SEQUENCE statement that default expression depends on --
    # it must exist before the 'cases' table is created below. This is a
    # deliberate manual-DDL element, flagged explicitly during Step 12Q's
    # architecture review (see app.models.case.CASE_NUMBER_SEQUENCE's own
    # docstring). Never regenerated via COUNT(*)/max()+1 -- a native
    # sequence guarantees uniqueness under concurrent case creation with
    # no read-then-write race window.
    op.execute("CREATE SEQUENCE case_number_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_number', sa.Integer(), server_default=sa.text("nextval('case_number_seq')"), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("priority IN ('critical', 'high', 'medium', 'low')", name='ck_cases_priority_valid'),
    sa.CheckConstraint("status IN ('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED')", name='ck_cases_status_valid'),
    sa.CheckConstraint('length(btrim(description)) > 0', name='ck_cases_description_not_blank'),
    sa.CheckConstraint('length(btrim(title)) > 0', name='ck_cases_title_not_blank'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ix_cases_created_at', 'cases', ['created_at'], unique=False)
    op.create_index('ix_cases_owner_id', 'cases', ['owner_id'], unique=False)
    op.create_index('ix_cases_priority', 'cases', ['priority'], unique=False)
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_table('case_alerts',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('linked_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('case_id', 'alert_id')
    )
    op.create_index('ix_case_alerts_alert_id', 'case_alerts', ['alert_id'], unique=False)
    op.create_table('case_audits',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('related_alert_id', sa.UUID(), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(action IN ('CASE_ALERT_LINKED', 'CASE_ALERT_UNLINKED') AND related_alert_id IS NOT NULL) OR (action NOT IN ('CASE_ALERT_LINKED', 'CASE_ALERT_UNLINKED') AND related_alert_id IS NULL)", name='ck_case_audits_related_alert_id_matches_action'),
    sa.CheckConstraint("action IN ('CASE_CREATED', 'CASE_TITLE_CHANGED', 'CASE_DESCRIPTION_CHANGED', 'CASE_STATUS_CHANGED', 'CASE_PRIORITY_CHANGED', 'CASE_OWNER_CHANGED', 'CASE_ALERT_LINKED', 'CASE_ALERT_UNLINKED', 'CASE_CLOSED', 'CASE_REOPENED')", name='ck_case_audits_action_valid'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_alert_id'], ['alerts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_audits_actor_user_id', 'case_audits', ['actor_user_id'], unique=False)
    op.create_index('ix_case_audits_case_id', 'case_audits', ['case_id'], unique=False)
    op.create_index('ix_case_audits_created_at', 'case_audits', ['created_at'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(body)) > 0', name='ck_case_notes_body_not_blank'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_notes_case_id', 'case_notes', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_notes_case_id', table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index('ix_case_audits_created_at', table_name='case_audits')
    op.drop_index('ix_case_audits_case_id', table_name='case_audits')
    op.drop_index('ix_case_audits_actor_user_id', table_name='case_audits')
    op.drop_table('case_audits')
    op.drop_index('ix_case_alerts_alert_id', table_name='case_alerts')
    op.drop_table('case_alerts')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_priority', table_name='cases')
    op.drop_index('ix_cases_owner_id', table_name='cases')
    op.drop_index('ix_cases_created_at', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###

    # Hand-added: reverse the hand-added CREATE SEQUENCE above, after the
    # table that depends on it as a column default has already been dropped.
    op.execute("DROP SEQUENCE case_number_seq")
